import Head from "next/head";
import SearchBox from "../../components/SearchBox";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Weather App - Accesa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="home">
        <div className="container">
          <SearchBox placeholder="Search for a city..." />
        </div>
      </div>
    </div>
  );
}
